apiVersion: playlist.spotify.crossplane.io/v1alpha1
kind: Playlist
metadata:
  name: crossplane-can-play-music
spec:
  forProvider:
    name: "Crossplane can play music"
    description: "Created using crossplane-contrib/provider-spotify Feel free to submit your favorite tracks to this playlist by opening a PR to https://github.com/tampakrap/spotify-playlists-as-code"
    public: true
    tracks:
      - "5Mri1bQdUrkcOkgZuudO16"
      - "0BZMYVlHBQt3X4oqizPEDR"
      - "2FVFnSm4CQzDxJBVyzWHsR"
  providerConfigRef:
    name: default
